### ISSUE TITLE
[Question] Does servez cache files?

### ISSUE THREAD

**Issue by rowild** [greggman/servez-cli#2]
With webpack, I keep changing files quite a bit and the reflections are shown in the files in the build folder. But for some reason, when I start servez from the build folder, it shows me old files. This happens in various browsers, where I didn't even call the url before, and it also happens when using different ports.

I assume that servez is caching files somewhere, but I have no clue, where? (I am on a mac.)
Am I mistaken? Do you have any idea, what could be going on here?
Thank you!

EDIT:
Actually, in the console, after a restart, it shows me:
`server started on ::8084 for path: /Volumes/_II_/.Trashes/501/public 08-51-56-193`

This happens, even though I start  servez from the public folder of my project. Why does this "relink" to a trashed version happen and how can I get rid of it?

**Comment by rowild** [comment]
It seems that, when the public folder is trashed while servez is running, servez keeps a reference to that folder. Only after a complete restart of VScode and emptying the trash bin, servez works fine again.

**Comment by greggman** [comment]
which platform? MacOS? And this is the app version of Servez or the command line version (just checking, I know this the command line version repo)

**Comment by rowild** [comment]
OS: Mac (as I wrote and can be seen in the path structure)
Version: cli.

I am in the habit of manually deleting or renaming the build folder from where servez starts up. (I do this to compare files sizes, because purgeCss is giving me a hard time...) Whenever I do this, servez remembers the trashed or renamed version. Only after a complete restart of VScode servez accesses the right folder again.

**Comment by greggman** [comment]
That's strange. I just tried serving a folder, loading a file from that folder in the browser, then dragging the folder to the trash, making a new folder, saving the file again from my editor, and everything worked. I also tried with vscode. Opened a folder, made a subfolder, put a file in the subfolder, served the subfolder, open file in browser, trashed the subfolder from vscode, made a new subfolder (same name) in vscode, made a new file, changes showed in the browser.

I wonder what it could be.

**Comment by greggman** [comment]
servez shouldn't be remembering anything so that's stange.

**Comment by greggman** [comment]
Are you running servez inside vscode? or are you running in a terminal?

**Comment by rowild** [comment]
Probably the OS is "doing something" to servez. Maybe it has to do with the way paths are remembered.

I run servez from inside VScode, where I usually have 2, 3 terminals open, one of which is rooted in the project's `public` subfolder. That's the one that handles servez...

But I have a strong feeling this is a OS problem, not a servez problem. simple, because this also happens, when you delete a Word file while you edit it: the file stays open, even though it was moved to a different location.

**Comment by greggman** [comment]
It might be an OS problem but I'd still like to know how to repeat it so I know what's going on.

I tried opening a terminal in VSCode, running servez on a subfolder in the VSCode project, opening a file in that subfolder in the browser, deleting the subfolder in vscode, making a new subfolder with the same name in vscode, making a new file with the same name in that subfolder, checking the file in the browser. Nothing was cached.

I wonder what else it might be.

**Comment by greggman** [comment]
Ok, now I tried opening 2 terminals in VSCode, serving a build folder in one terminal, building in the other terminal, checking I can open a built file in the browser, then I edited a file, ran the build again (which deletes the build folder and then regenerates the filles), then I checked in the browser and the file I edited showed up as expected.

Maybe I need to to use webpack for the build or something

**Comment by rowild** [comment]
I am preparing a little video of my workflow. Gimme a moment please... and let me know where I can send it to, please

**Comment by greggman** [comment]
Can you just drop video in here in the issue? Another thing that might be useful is if you could make a "hello world" example with your setup including a package.json that has your devDependencies, zip it up and drop it here make a github repo .

**Comment by rowild** [comment]
Slimmed down repo:
https://github.com/rowild/purgecss-tailwind-problem

In case you wonder:
The repo was made for the first 2 issues here:
 https://github.com/FullHuman/purgecss/issues
(Wouldn't mind some help on the purgeCss problem.  :-)  )

The video is zipped, because mp4 is not supported:
[servez.mp4.zip](https://github.com/greggman/servez-cli/files/4651123/servez.mp4.zip)

**Comment by greggman** [comment]
thanks for the video. I see the issue is not servez, it's the OS. The OS is keeping the current directory and that directory is getting moved to the trash.

Instead of 

```
cd public
servez
```

try

```
servez public
```

**Comment by rowild** [comment]
Yepp, I thought so, too. Sorry for wasting your time, but also thank you for sticking with me!

Using the path parameter was actually something i wanted to look up. Now you helped me out here - thanks again! :-)

Stay safe!

**Comment by greggman** [comment]
Tell me if it solved the issue.

**Comment by rowild** [comment]
Yes. Now, when I delete the "public" folder, stop "servez" and start "servez public" again, I get an error message saying that 
"'/Volumes/[path]/public' does not exist."

Great! Thanks!

**Comment by greggman** [comment]
args!!! That's strange and unexpected too 😓

**Comment by greggman** [comment]
Well, ok, it's not unexpected if public does not exist. I suppose I could make that a warning.

**Comment by rowild** [comment]
Why? I deleted the "public" folder. It should not be there anymore, which servez recognised totally correctly on its next startup. 
What's wrong with that in your opinion?

**Comment by greggman** [comment]
I pushed version 1.8.0 which just prints a warning that the folder does not exist.

I originally made it fail because some other servers did not fail *and* did not print a warning and sometimes I'd type something wrong or be in the wrong place and kept wondering why it wasn't finding the files so I made servez fail.

But, I see from your example that maybe a warning is better since you might want to do `servez build-folder` in one terminal even before you built and then in another terminal start the build.

**Comment by rowild** [comment]
Will check that. But I wonder:  servez will run "empty" and give a warning - and then, once the build folder exists, it will automagically recognise it?

**Comment by rowild** [comment]
Ok, tried it. I think it will make sense over time. Currently I am used to the message that the folder does not exist and therefore the server does not start. Which seems cleaner and also safer to me. But let's see how fast my workflow will adopt... :-)

Thank you! Have a good day!
