### ISSUE TITLE
Add an option to disable logs

### ISSUE THREAD

**Issue by vicb** [greggman/servez-cli#3]
First thanks for you great server, it's much than http-server!

Would it be possible to add an option  to disable logs? (http server as `-s`).

Thanks

**Comment by greggman** [comment]
meaning you just want it to print nothing period? Can you don't just want to do `servez >/dev/nul` or equivilent?

**Comment by vicb** [comment]
Ideally the server info would still be logged:

```
server started on ::8080 for path: /path/to/root
available on:
   http://localhost:8080
   http://127.0.0.1:8080
   http://192.168.66.205:8080
press CTRL-C to stop the server.
```

But no requests log (either ok or error).

If it's too much of a pain to add `>/dev/null` would be a workaround.

Thanks

**Comment by greggman** [comment]
added -q  (or --quiet) to v2.1.0

**Comment by vicb** [comment]
Thank you so much!
